import Lake
open Lake DSL

package PPGraph where
  leanOptions := #[
    ⟨`autoImplicit, false⟩
  ]

require mathlib from git
  "https://github.com/leanprover-community/mathlib4" @ "master"

@[default_target]
lean_lib PPGraph where
  srcDir := "."
  roots := #[`PPGraph, `PPGraphCategorical, `PPGraphMeta,
             `PPGraphRepair, `PPGraphRR, `PPGraphParametric,
             `PPGraphParametricQuotient, `PPGraphBlocking,
             `PPGraphQuotientBridge, `PPGraphSelection, `PPGraphEquivBridge, `PPGraphComplementarySlackness, `PPGraphSelfAssessment, `PPGraphAssessmentBridge, `PPGraphProbabilistic, `PPGraphLLL, `PPGraphMoserTardos, `PPGraphMoserTardosProcess, `PPGraphMoserTardosWitness, `PPGraphMoserTardosGrowing, `PPGraphMoserTardosInjectivity, `PPGraphMoserTardosWeight, `PPGraphMoserTardosConvergence, `PPGraphMoserTardosLogSpace, `PPGraphMoserTardosRandomTrajectory, `PPGraphMoserTardosCounting, `PPGraphMoserTardosPastIndependence,
             `PPGraphLopsidedLLL, `PPGraphVariableLLL, `PPGraphBDD, `PPGraphBDDMoserTardos,
             `PPGraphBDDCost, `PPGraphBDDMatrix, `PPGraphBDDLaplacian, `PPGraphBDDCount,
             `PPGraphMoserTardosCheckOrder, `PPGraphMoserTardosCheck,
             `PPGraphMoserTardosCheckBirth, `PPGraphMoserTardosCorrespondence,
             `PPGraphMoserTardosProbability, `PPGraphMoserTardosWeightSum, `PPGraphMoserTardosRealTree,
             `PPGraphMoserTardosExpectation, `PPGraphMoserTardosCanonical,
             `PPGraphMoserTardosInjectivityBridge, `PPGraphMoserTardosCheckInvariance,
             `PPGraphMoserTardosCheckShape, `PPGraphMoserTardosCheckBridge,
             `PPGraphMoserTardosProbabilityGeneral, `PPGraphMoserTardosWTreeToGrowingTree,
             `PPGraphMoserTardosLabelsAtDepthBridge, `PPGraphMoserTardosToGrowingTreeCheckBridge,
             `PPGraphMoserTardosWTreeCountable, `PPGraphMoserTardosResamplingCount,
             `PPGraphMoserTardosRandomInitialization, `PPGraphMoserTardosRandomInitExpectation,
             `PPGraphMoserTardosOccurrence, `PPGraphMoserTardosOccurrenceCounting,
             `PPGraphMoserTardosOccurrenceProbability, `PPGraphMoserTardosWitnessFamily,
             `PPGraphMoserTardosOccurrenceExpectation,
             `PPGraphMoserTardosTermination, `PPGraphMoserTardosConstantLog,
             `PPGraphMoserTardosRepairBridge, `PPGraphMoserTardosPegden,
             `PPGraphShearerPolynomial, `PPGraphShearerInduction,
             `PPGraphShearerBDD, `PPGraphShearer, `PPGraphShearerMT,
             `PPGraphShearerStable, `PPGraphShearerWitness,
             `PPGraphShearerLayerProfile, `PPGraphShearerOccurrence,
             `PPGraphShearerSequenceProbability, `PPGraphShearerExpectation,
             `PPGraphBDDPartition, `PPGraphShearerBDDBudget,
             `PPGraphShearerComponentOccurrence, `PPGraphShearerBDDExpectation,
             `PPGraphMoserTardosIntersection, `PPGraphHLSParameters,
             `PPGraphShearerSlack, `PPGraphShearerSlackExpectation,
             `PPGraphHLSMatching, `PPGraphHLSReversal, `PPGraphHLSWitnessDAG,
             `PPGraphHLSWitnessLayers, `PPGraphHLSStableEncoding,
             `PPGraphHLSCanonicalEncoding, `PPGraphHLSWitnessBudget,
             `PPGraphHLSTableCheck, `PPGraphHLSReversalSlots, `PPGraphHLSCoinSaving,
             `PPGraphHLSPrefixCheck, `PPGraphHLSSwappedTests, `PPGraphHLSLabelRanks,
             `PPGraphHLSNormalization, `PPGraphHLSNormalizationCheck,
             `PPGraphHLSTimeDAG, `PPGraphHLSRealDAG, `PPGraphHLSRealDAGCounts,
             `PPGraphHLSCliqueRanks, `PPGraphHLSPairKeys, `PPGraphHLSFiniteDAG,
             `PPGraphHLSOrientationScore, `PPGraphHLSAugmentedExistence,
             `PPGraphHLSParitySelection, `PPGraphHLSMatchingSelection,
             `PPGraphHLSDecoratedBudget, `PPGraphHLSQueryLaw, `PPGraphHLSBlockAssembly,
             `PPGraphHLSBlockIntersection, `PPGraphHLSFootprintBlocks,
             `PPGraphHLSExpansionDecoder, `PPGraphHLSBlockQueries,
             `PPGraphHLSPairProbability, `PPGraphHLSOrderedDAG,
             `PPGraphHLSTopologicalOrder, `PPGraphHLSExpansionVertices,
             `PPGraphHLSExpansionGraph, `PPGraphHLSOrderedReversal,
             `PPGraphHLSExpansionReversibility, `PPGraphHLSAugmentedSpace,
             `PPGraphHLSNormalizationReversal, `PPGraphHLSOriginRecovery,
             `PPGraphHLSColoredExpansion, `PPGraphHLSNodeIso, `PPGraphHLSOriginalIso,
             `PPGraphHLSMatchingArcUniqueness, `PPGraphHLSChoiceRecovery,
             `PPGraphHLSExpansionFamily, `PPGraphHLSExpansionWeight,
             `PPGraphHLSChoiceSum, `PPGraphHLSRelativeCoins,
             `PPGraphHLSAugmentedCoordinates, `PPGraphHLSRefinedBudget,
             `PPGraphHLSCoinQueryLaw, `PPGraphHLSAugmentedPair,
             `PPGraphHLSAugmentedDependence, `PPGraphHLSUnitChecks,
             `PPGraphHLSProductDiscount, `PPGraphHLSOrdinalOccurrence,
             `PPGraphHLSRefinedProbability, `PPGraphHLSRootUnion,
             `PPGraphHLSExpectation, `PPGraphHLSRepairBridge,
             `PPGraphMoserTardosPolicy, `PPGraphHLSPolicyDAG,
             `PPGraphHLSPolicyCounting, `PPGraphHLSPolicyExpectation,
             `PPGraphMoserTardosHistoryPolicy,
             `PPGraphInfeasibility, `PPGraphFiniteFeasibility,
             `PPGraphUnsatisfiableCore, `PPGraphInfeasibilityCounting,
             `PPGraphFiniteCore, `PPGraphBDDInfeasibility, `PPGraphFarkasCertificate,
             `PPGraphReachabilityRefutation, `PPGraphRepairDecision,
             `PPGraphMoserTardosInfeasibility, `PPGraphCertifiedDecision,
             `PPGraphHLSDecisionBridge, `PPGraphCorrectionDuality,
             `PPGraphRepairUndecidability, `PPGraphFiniteAbstraction,
             `PPGraphFiniteAbstractionRepair, `PPGraphAdditiveDrift,
             `PPGraphMoserTardosDrift, `PPGraphMoserTardosFullResampling,
             `PPGraphMoserTardosDriftCost, `PPGraphMoserTardosDriftRegion,
             `PPGraphFiniteDrift, `PPGraphFiniteDriftProcess,
             `PPGraphFiniteUpdate, `PPGraphFiniteUpdateIID, `PPGraphFiniteResampling,
             `PPGraphFiniteTable, `PPGraphFiniteTableLaw, `PPGraphFiniteMTDrift,
             `PPGraphFinitePotential, `PPGraphFinitePotentialMT,
             `PPGraphFinitePotentialExpectation, `PPGraphFinitePotentialExpectationMT,
             `PPGraphFinitePotentialRefutation,
             `PPGraphFinitePotentialTail,
             `PPGraphFinitePotentialTailCertificate, `PPGraphFinitePotentialTailMT,
             `PPGraphFiniteLumping, `PPGraphFiniteLumpingUpdate]
